- src/Transport/Http.php
Свойство уже задаётся в конструкторе ClickHouseDB\Client, а указание его здесь делает настройку бесполезной, т.к. значение всегда перезаписывается на 1.
> Prevent the value of the ‘extremes’ setting from being overwritten

- src/Transport/Http.php
Добрый день, спасибо за библиотеку.
Добавил для возможности доступа к напрямую к курлеру Client->transport()->getCurler() (иногда бывает нужно).
> Getter&setter for curler, refactoring

- src/Quote/StrictQuoteLine.php
пример, на котором валилось:
string\\
(слеш на конце)
$clickhouse->insert("table", [["string\\"]], ["somecolumn"])
> fix: кодируем символ кодирования

- composer.json
- include.php
- src/Client.php
- tests/InsertAssocTest.php
Добавил возможность вставлять с помощью ассоциативного массива. Иногда это сильно удобнее.
Добавил немного тестов для этого, плюс пришлось пошаманить с настройками в composer.json - иначе phpUnit не запускался.
Во-первых, проблема с версией (6.x уже по другому несколько работает), во-вторых у вас под гитом нет tests/test_functions.php - все это пришлось выплить.
> Insert with associative array

- src/Query/Degenerations/Bindings.php
Fixes #34 
```
"before" => "'Escape ' when using words like it's'"
"after"  => "'Escape \' when using words like it\'s'"
```
> refs #29508. [Bug] Escape values

- src/Query/Degenerations/Bindings.php
- tests/BindingsTest.php
Array parameters aren't escaped.
```
select * from test. WHERE id IN (:id)
```
Parameters:
```php
['id' => ['1', "2') OR ('1'='1"]]
```
Expected:
```
select * from test. WHERE id IN ('1','2\') OR (\'1\'=\'1')
```
Actual:
```
select * from test. WHERE id IN ('1','2') OR ('1'='1')
```
> Escape an array

- src/Transport/StreamInsert.php
Previous version work fine for small files, but when I begun to stream big files in loop it was very slow.
New version use one connect and work fast
> FIX: one stream work faster and safe than loop

- .travis.yml
- composer.json
- phpstan.neon
- src/Exception/Exception.php
- src/Statement.php
- tests/ClientTest.php
I have added code quality check tool. It runs static analysis over the code and reports issues https://github.com/phpstan/phpstan
Currently I setup it to use level 1. There are I think 7 levels in total, each introduces higher strictnes.
We can increase levels over time and improve the quality of code base.
The issues fixed in https://github.com/smi2/phpClickHouse/pull/58/commits/cc64fdf93861945a6d16a1f217ed4ea04342ac7f were discovered by running this tool
> Add PHPStan

- .gitignore
- .travis.yml
- composer.json
- phpcs.xml.dist
- src/Query/Query.php
I have added a CI check for coding standard https://github.com/doctrine/coding-standard
It is set in a way that CI only checks the changed lines in pull requests and validates them against coding standard so there's no need to change to whole codebase for now.
I recommend to check into the branch, run `composer install` and then eg. `vendor/bin/phpcs src/Query/Degeneration/Bindings.php` so you can see what it does.
Also I have made changes to `toSql()` function in Query.php so it is in compliance with CS as a preview. Added a typehint so it is a BC break.
When changed lines are not compliant with CS, it reports it in Travis
Let me know what you think and whether we will merge this or not.
> Add Coding Standard

- src/Query/Degeneration/Bindings.php
I'm kind of used to this behavior from eg. [DBAL](https://github.com/doctrine/dbal/blob/87251a14b20107cf3015bd790e1f1f6c380bda42/lib/Doctrine/DBAL/Types/DateImmutableType.php#L50). I don't want to format datetime in every place I pass it to the query as this client can safely convert it for me.
> Convert DateTimeInterface param to Clickhouse's datetime format

- src/Query/Degeneration/Bindings.php
- tests/BindingsTest.php
I passed some integers as parameters but they were converted to string and therefore type mismatch occured in ClickHouse.
> Do not convert int parameters in array to string

- src/Quote/StrictQuoteLine.php
- tests/StrictQuoteLineTest.php
Follows https://github.com/smi2/phpClickHouse/pull/86
> Fix escape

- src/Query/WriteToFile.php
https://clickhouse.yandex/docs/en/interfaces/formats/#csvwithnames
> fix: add CSVWithNames to supported formats

- src/Statement.php
After clean install new release 19.5.2.6 via docker, ClickHouse server errors ends with:
` (version 19.5.2.6 (official build))`
Before:
`, e.what() = DB::Exception`
> fix clickhouse release 19.5.2.6 error parsing

- src/Query/WriteToFile.php
In case of work with arrays in response values CSV isn't good format.
JSONEachRow works fine and easier to decode.
BTW: I've seen that constant names must be written in upper case (https://github.com/smi2/phpClickHouse/pull/107#discussion_r236236834)
> WriteToFile: support for JSONEachRow format

- src/Exception/QueryException.php
- src/Statement.php
- src/Transport/CurlerRequest.php
- src/Transport/CurlerResponse.php
Added more debug info for the response without any error message and with http error code only.
The additional details from `QueryException` can be logged in try/catch block.
> Added more debug info for empty response with error

- src/Query/Query.php
sometimes we write the sql, and end with `;`, but it will throw an exception in `phpClickHouse`, even it is not an error. So we can cut this `;` when we detect it;
> fix the exception(multi-statement not allow) when sql end with ';'

- composer.json
- example/00_config_connect.php
- src/Client.php
- src/Transport/CurlerRequest.php
- src/Transport/Http.php
Two new types of authentication have been added
- HTTP Basic Authentication
- With URL parameters
The client can specify the authentication method by
specifying the "auth_method" in the `$connectParams`.
Now the client can authenticate using three authentication
methods, as described in the documentation:
https://clickhouse.tech/docs/en/interfaces/http/.
The signature of the `Http` class constructor has been
changed. A new optional argument `$authMethod` has been
added.
> Add two new types of authentication

- .scrutinizer.yml
- .travis.yml
- composer.json
- tests/BindingsTest.php
- tests/ClientTest.php
- tests/ConditionsTest.php
- tests/FormatQueryTest.php
- tests/JsonTest.php
- tests/ProgressAndEscapeTest.php
- tests/SessionsTest.php
- tests/StreamTest.php
- tests/StrictQuoteLineTest.php
- tests/Type/UInt64Test.php
I'm going to use PHP 8 in a project and this library's dependencies are quite out of date.
It's time to move forward. I see no reason for this library support versions below 7.3.
I suggest we can bump the version to 1.4 with only support for PHP ^7.3 and ^8.0.
I took the initiative to make some changes and fix some tests but I couldn't fix them all. So anyway we could start from this point.
> Drop unsupported PHP versions and upgrade to PHP 7.3+

- src/Client.php
- src/Settings.php
Hello, when I try to set the enable_http_compression parameter through the `$settings` parameter of the constructor, it is replaced by the last line of the constructor which calls `enableHttpCompression` always at true.
I set enable_http_compression to true in default settings and removed that call. This change prevents overwriting.
> Fix: prevent enable_http_compression parameter from being overridden

- src/Client.php
- src/Settings.php
- src/Transport/CurlerRequest.php
- src/Transport/Http.php
Currently setConnectTimeOut(0.5) will set CURLOPT_CONNECTTIMEOUT to 0 because of type conversion.
Ive fixed typing and replaced CURLOPT_CONNECTTIMEOUT with CURLOPT_CONNECTTIMEOUT_MS.
> Support floats in timeout and connect_timeout

- composer.json
- Since using the `Composer 2.2` version, the Composer plugin need to be set in the `composer.json` file. Otherwise it will cause the following exception message when running the `composer update` command:
```
.......
dealerdirect/phpcodesniffer-composer-installer contains a Composer plugin w  
hich is blocked by your allow-plugins config. You may add it to the list if  
you consider it safe.                                                       
You can run "composer config --no-plugins allow-plugins.dealerdirect/phpcod  
esniffer-composer-installer [true|false]" to enable it (true) or disable it  
explicitly and suppress this exception (false)                              
See https://getcomposer.org/allow-plugins
.......
```
> Add allow_plugins setting since Composer 2.2.x

- src/Transport/Http.php
Problem:
If we use distributed queries to write, as example
```SQL
DROP TABLE IF EXISTS test_table ON CLUSTER test_cluster
```
the answer will be contains metadata in table format which can't be parsed in `ClickHouseDB\Statement::init()` and as a result throws "_Can`t find meta_" exception.  
This pr fixed it by adding JSON format for queries started from CREATE, DROP or ALTER.  
This does not affect on non-distributed queries as the response to these queries contains nothing for those type of queries.
> Distributed queries response metadata

- src/Client.php
This problem occurs because that syntax is supported only for PHP 8.0 and higher. Using it breaks support for PHP7.
In this pull request, I moved the parameter requirements from attribute definition to phpdoc to fix this problem.
> Fixed Issue #206 Php syntax error in php ^7.3

- src/Statement.php
- tests/StatementTest.php
Fixes issue https://github.com/smi2/phpClickHouse/issues/144
This problem occurs on partially flushed response to the client with 200 status code with further ClickHouse exception.
All details in StatementTest::testIsErrorWithOkStatusCode
I've used _preg_match_ instead of _stripos_ (suggested in https://github.com/smi2/phpClickHouse/issues/144) because regexes precompiles and further calls are much cheaper (about 10 times in my tests of clickhouse error regex). Also _stripos_ speed only 30% faster (and less) than first call of _preg_match_ on string from 10MB to 1000MB.
> Fixed silent error occurrence on 200 http status code (ExceptionWhileProcessing query error)

- src/Transport/Http.php
That changes https://github.com/smi2/phpClickHouse/pull/190 prevent that queries from being executed:
`CREATE FUNCTION ...` or  `DROP FUNCTION ...`
The proposed solution in [pull request #214](https://github.com/smi2/phpClickHouse/pull/214) resolves this specific issue. However, it's essential to acknowledge that this fix might introduce potential compatibility issues with existing codebases.
It seems that the changes made in https://github.com/smi2/phpClickHouse/pull/190 addressed a specific case, but other common scenarios may have been overlooked, so I've implemented an early exit from function when `ON CLUSTER` does not exist.
> Do not add unexpected FORMAT JSON for not distributed queries

- src/Client.php
Fixing return type in DocBlock.
Checked code deeper:
```php
public function getTimeOut(): int
{
return intval($this->get('max_execution_time'));
}
```
> Fix getTimeout method return type

- src/Transport/Http.php
**Problem**:
Similar to issue described in #190, when executing RENAME queries (RENAME TABLE, etc.) on distributed ClickHouse clusters, the response contains metadata in table format which cannot be parsed by ClickHouseDB\Statement::init(), resulting in `Can't find meta` exception.
**Solution**:
This PR extends the fix from #190 to include RENAME queries by adding JSON format for queries starting with "RENAME". This ensures proper metadata parsing for distributed RENAME operations while maintaining backward compatibility with non-distributed queries.
**Release Request**:
Could you please consider creating a new release after merging this PR? This fix addresses a critical issue that prevents RENAME operations from working in distributed environments, and having it available in a tagged …
> Fix metadata parsing for distributed RENAME queries
