src/Quote/StrictQuoteLine.php
Clickhouse support NULL values, but phpClickHouse can not insert NULL.
=> support NULL values for insert

README.md
=> Normalize formatting in README

src/Client.php, src/Transport/StreamInsert.php, tests/ClientTest.php
The StreamInsert class is not enough  flexible. I added few fixes to improve your code
In addition wrote test cases for StreamInsert class
=> Add flexibility to StreamInsert class

composer.json
No need to have version in composer.json as it's saved @ github -> packagist
=> Cleanup Composer.json

.scrutinizer.yml, .travis.yml, README.md, phpunit.xml.dist
👍 on adding CI checks, looks neat and I feel save adding new things now ;)
I noticed you added badges to the readme, it looks mature now cool. I took the liberty to make a small reformatting
- use https://img.shields.io/ as it is used in I dare to say 95 % of repositories
- I'd rather not to use html in markdown
Also I noticed the coverage was not working so I fixed it and added code quality metric. 
More coming later, have a nice day
=> Scrutinizer with coverage

src/Statement.php
@isublimity requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/smi2/phpClickHouse/
=> Scrutinizer Auto-Fixes

src/Client.php, src/Transport/Http.php, tests/ClientTest.php
```markdown
- Added new method `getServerVersion()` to Client to get string with server version.
- Moved logic of method `ping()` to transport level and changed according to official guide.
```
[Official guide](https://clickhouse.yandex/docs/en/interfaces/http_interface/#http-interface) by using HTTP interface
=> Added getServerVersion() method to Client. Changed ping() method.

src/Transport/Http.php
https://github.com/smi2/phpClickHouse/issues/77
Please review and merge
=> FIX: Doesn't append port if empty or null

src/Client.php, tests/ClientTest.php, tests/FormatQueryTest.php
some cleanup
notice change in `__construct` for settings setup
=> Client cleanup

composer.json
I'll just leave it here, merge whenever you like.
Just reminding that 7.0 is EOLed in 2 months, 7.3 out soon.
=> Bump to php 7.1

src/Client.php, src/Exception/QueryException.php, tests/ClientTest.php
=> Do not allow to execute insert with empty values

src/Transport/CurlerRolling.php
The method does not work correctly due to checking for the number of iterations. Also a little cleaned the method from unnecessary things
=> Fix: async loop breaks after 20 seconds

composer.json, src/Client.php, src/Settings.php, src/Transport/CurlerRequest.php, src/Transport/Http.php
Usage: 
```php
$config = [
'host' => 'XXXX.mdb.yandexcloud.net,
'port' => '8443',
'username' => 'user',
'password' => 'pwd',
'https' => true,
'sslCA' => '/path/to/certificate.pem',
];
$db = new ClickHouseDB\Client($config);
```
=> Add client certificate support to able to work with Yandex ClickHouse cloud hosting

src/Exception/ClickHouseUnavailableException.php, src/Statement.php
This exception extends `Exception\QueryEception` for compatibility reason.
=> Enhancement: Add a new exception to be able to distinguish that ClickHouse is not available.

src/Client.php
Fixed typo in streamRead exception text.
=> Fixed typo in streamRead exception text

composer.json
mb_strlen() in src/Transport/CurlerRequest.php:739 require mbstring
=> add mbstring to composer require

src/Client.php, src/Query/Degeneration.php, src/Query/Degeneration/Bindings.php, src/Query/Degeneration/Conditions.php, src/Query/Query.php, src/Transport/Http.php, tests/BindingsPostTest.php, tests/ClientTest.php
Closes #151
Post type bindings support from the dev23 branch, with array support addition and test.
=> Post type bindings support

.gitattributes
Does not download development files to user project
=> remove dev files for --prefer-dist

src/Quote/StrictQuoteLine.php, src/Transport/Http.php
https://github.com/smi2/phpClickHouse/issues/202
https://github.com/smi2/phpClickHouse/issues/194
=> fix(#202): Fix converting boolean when inserting into int and fix(#194): Fix unexpected readonly mode with specific string in query

src/Client.php
`ClickHouseDB\Transport\Http` awaits integer port. But now it might receive a string.
=> Fix connect port type

src/Settings.php, src/Transport/Http.php
Both of these settings are not using.
=> Remove unused Settings properties

src/Client.php
in last commit there were mistake in method name change
=> fix session id configuration

src/Statement.php, tests/StatementTest.php
https://github.com/smi2/phpClickHouse/issues/223
=> fix(statement): Avoid Marking Responses as Failed When Data Contains DB::Exception Text as a Value
